apiVersion: v1
kind: Service
metadata:
  name: java-summary-service-lb
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: java-summary-service